baseURL: "https://kevinchen1994.github.io/"
theme: hugo-PaperMod
languageCode: "en-us"
title: "厨师海森堡的厨房"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: /posts/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10
        - name: Categories
          url: /categories/
          weight: 15
        - name: Search
          url: /search/
          weight: 20  
        - name: About Me
          url: /about/
          weight: 25
          
params:
    env: production
    homeInfoParams:
        Title: "欢迎来到我的厨房"
        Content: "👋嗨，我是Kevin，一个自然语言处理算法工程师，更是一个热爱生活的编程少年，INFJ-A。\n

                  \n

                  笔记是总结知识增援未来的自己，写作是对未来要认识你的人的自我介绍。\n\n

                  这个博客主要用来记录我的学习、生活、思考，你可以通过标签筛选你感兴趣的内容。\n\n
                  
                  如果你想了解我，可以在About Me页面进行查看。\n\n"
                
    socialIcons:
        - name: github
          url: "https://github.com/kevinchen1994"

    # share button      
    ShowShareButtons: true
    # showreading time
    ShowReadingTime: true

    ShowPostNavLinks: true
    # Code copy button
    ShowCodeCopyButtons: true

assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary


    