baseURL = "https://kevinchen1994.github.io/"
languageCode = "en-us"
title = "厨师海森堡的厨房"
theme = "hugo-PaperMod"

# 版权描述，仅仅用于 SEO
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."



[params]
# 主页信息设置
  [params.homeInfoParams]
    title = "kevin"
    # 主页显示的网站副标题
    content = "👨🏻‍💻热爱生活的编程少年|🏃不严肃跑者|🧠NLPer"

  [params.socialIcons]
    - name = "github"
      url = "https://github.com/kevinchen1994"
    - name = "email"
      url = "346521888@qq.com"


# 菜单配置
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "所有文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "类别"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5

# 文章页面配置
[page]
  # 是否使用系列导航
  seriesNavigation = true
  # 是否启用最后修改时间
  enableLastMod = true
  # 是否启用字数统计
  enableWordCount = true
  # 是否启用阅读时间估计
  enableReadingTime = true
   # 目录配置
  [page.toc]
    # 是否使用目录
    enable = true
    # 是否保持使用文章前面的静态目录
    keepStatic = false
    # 是否使侧边目录自动折叠展开
    auto = true
  # 文章页面的分享信息设置
  [page.share]
    enable = true
    Twitter = true
    Weibo = true