baseURL = "https://kevinchen1994.github.io/"
languageCode = "en-us"
title = "厨师海森堡的厨房"
theme = "PaperMod"
# 默认每页列表显示的文章数目
paginate = 10
# 版权描述，仅仅用于 SEO
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."




# 菜单配置
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "所有文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "类别"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "series"
    name = "系列"
    url = "/series/"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    name = ""
    url = "https://github.com/kevinchen1994"
    weight = 10

[params]
# 主页信息设置
  [params.home]
    [params.home.profile]
      # 主页显示的网站标题 (支持 HTML 格式)
      title = "kevin"
      # 主页显示的网站副标题
      subtitle = "👨🏻‍💻热爱生活的编程少年|🏃不严肃跑者|🧠NLPer"
      # 主页显示头像的 URL
      avatarURL = "https://s1.ax1x.com/2023/08/15/pPQAI4H.png"
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = "346521888@qq.com"

# 文章页面配置
[page]
  # 是否使用系列导航
  seriesNavigation = true
  # 是否启用最后修改时间
  enableLastMod = true
  # 是否启用字数统计
  enableWordCount = true
  # 是否启用阅读时间估计
  enableReadingTime = true
   # 目录配置
  [page.toc]
    # 是否使用目录
    enable = true
    # 是否保持使用文章前面的静态目录
    keepStatic = false
    # 是否使侧边目录自动折叠展开
    auto = true
  # 文章页面的分享信息设置
  [page.share]
    enable = true
    Twitter = true
    Weibo = true
  # 评论系统设置
  [page.comment]
    enable = true
    # Utterances comment 评论系统设置 (https://utteranc.es/)
    [page.comment.utterances]
      enable = true
      # owner/repo
      repo = "Hugo-DoIt/utterances-comments"
      issueTerm = "pathname"
      label = ""
      lightTheme = "github-light"
      darkTheme = "github-dark"

# 网站分析配置
[analytics]
  enable = true
  # Google Analytics
  [analytics.google]
    id = ""
    # 是否匿名化用户 IP
    anonymizeIP = true

# paper 配置
#[params]
#  color = 'linen'
#  github = 'kevinchen1994'
#  avatar = 'https://s1.ax1x.com/2023/08/15/pPQAI4H.png'
#  name = 'KevinChen'
#  bio = '👨🏻‍💻热爱生活的编程少年|🏃不严肃跑者|🧠NLPer'
  # misc
#  disableHLJS = true                        # disable highlight.js
#  monoDarkIcon = true                       # show monochrome dark 
#  comments = true                            # disable comments for a specific page
#  math = true                                 # enable KaTex math typesetting for a specific page


