baseURL: "https://kevinchen1994.github.io/"
theme: hugo-PaperMod
languageCode: "en-us"
title: "厨师海森堡的厨房"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: /posts/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10
        - name: Categories
          url: /categories/
          weight: 15
        - name: About me
          url: /about/
          weight: 20
          
params:
    env: production
    homeInfoParams:
        Title: "Test: my, garden!"
        Content: """
                This is the personal website of Ethan Rahn.
                
                I am a software engineer, specializing in cybersecurity.
                > - I deeply enjoy understanding a complex system, decomposing it, and finding where form does not meet intended function 🔍️
                > - I am most familiar with securing products (this may be referred to as "blue team" stuff) 🛡️
                > - I have an, unfortunate, familiarity with certification standards such as "FIPS 140" and "cPPND" (fka "Common Criteria") 📝️
                I enjoy reading about technology and imagining where it will take the world next.
                > - Admittedly, I take a pessimistic worldview on this. I blame my time spent on cybersecurity for this 🤦️
                """
      

    socialIcons:
        - name: twitter
          url: "https://test.com/"
        - name: stackoverflow
          url: "https://test.com/"
        - name: github
          url: "https://test.com/"
        - name: medium
          url: "https://test.com/"
        - name: linkedin
          url: "https://test.com/"

assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"