baseURL = "https://kevinchen1994.github.io/"
languageCode = "en-us"
title = "厨师海森堡的厨房"
theme = "hugo-PaperMod"
# 默认每页列表显示的文章数目
paginate = 10
# 版权描述，仅仅用于 SEO
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."




# 菜单配置
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "所有文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "类别"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "series"
    name = "系列"
    url = "/series/"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    name = ""
    url = "https://github.com/kevinchen1994"
    weight = 10

[params]
# 主页信息设置
  [params.home]
    [params.home.profile]
      # 主页显示的网站标题 (支持 HTML 格式)
      title = "kevin"
      # 主页显示的网站副标题
      subtitle = "👨🏻‍💻热爱生活的编程少年|🏃不严肃跑者|🧠NLPer"
      # 主页显示头像的 URL
      avatarURL = "https://s1.ax1x.com/2023/08/15/pPQAI4H.png"
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = "346521888@qq.com"
