baseURL = "https://kevinchen1994.github.io/"
languageCode = "en-us"
#title = "厨师海森堡的厨房"
theme = "DoIt"
# 默认每页列表显示的文章数目
paginate = 10
# 版权描述，仅仅用于 SEO
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
#subtitle = '👨🏻‍💻热爱生活的编程少年|🏃不严肃跑者|🧠NLPer'

# 主页信息设置
[home]
  [[home.profile]]
    # 主页显示的网站标题 (支持 HTML 格式)
    title = "厨师海森堡的厨房"
    # 主页显示的网站副标题
    subtitle = "👨🏻‍💻热爱生活的编程少年|🏃不严肃跑者|🧠NLPer"

# 菜单配置
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 1


[params.home.profile]
  # Gravatar 邮箱, 用于优先在主页显示的头像
  gravatarEmail = "346521888@qq.com"
  # 主页显示头像的 URL
  avatarURL = "https://s1.ax1x.com/2023/08/15/pPQAI4H.png"
  # 头像的链接指向的 URL
  avatarLinkURL = "https://s1.ax1x.com/2023/08/15/pPQAI4H.png"

[params.social]
  [params.social.email]
    # 排列图标时的权重 (权重越大, 图标的位置越靠后)
    weight = 10
    # 你的社交 ID
    id = "346521888@qq.com"
    # 你的社交链接的前缀
    prefix = ""
    # 当鼠标停留在图标上时的提示内容
    title = "Email"
  [params.social.github]
    # 排列图标时的权重 (权重越大, 图标的位置越靠后)
    weight = 0
    # 你的社交 ID
    id = "kevinchen1994"
    # 你的社交链接的前缀
    prefix = "https://github.com/"
    # 当鼠标停留在图标上时的提示内容
    title = "GitHub"


# paper 配置
#[params]
#  color = 'linen'
#  github = 'kevinchen1994'
#  avatar = 'https://s1.ax1x.com/2023/08/15/pPQAI4H.png'
#  name = 'KevinChen'
#  bio = '👨🏻‍💻热爱生活的编程少年|🏃不严肃跑者|🧠NLPer'
  # misc
#  disableHLJS = true                        # disable highlight.js
#  monoDarkIcon = true                       # show monochrome dark 
#  comments = true                            # disable comments for a specific page
#  math = true                                 # enable KaTex math typesetting for a specific page

# ------------------------------
# 配置网站菜单
#[menu]
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 10
#  [[menu.main]]
#    identifier = "friends"
#    name = "Friends"
#    url = "/friends/"
#    weight = 10
