baseURL = "https://kevinchen1994.github.io/"
languageCode = "en-us"
title = "厨师海森堡的厨房"
theme = "hugo-PaperMod"

# 版权描述，仅仅用于 SEO
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."


# home-info mode
[homeInfoParams]
  Title: "kevin"
  Content: 👨🏻‍💻热爱生活的编程少年|🏃不严肃跑者|🧠NLPer


# 菜单配置
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "所有文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "类别"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "series"
    name = "系列"
    url = "/series/"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5
