baseURL = "https://kevinchen1994.github.io/"
languageCode = "en-us"
title = "厨师海森堡的厨房"
theme = "hugo-PaperMod"

# 版权描述，仅仅用于 SEO
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."



[params]
# 主页信息设置
  [params.homeInfoParams]
    Title = "欢迎来到我们的厨房 👋"
    Content = "嗨，我是Kevin，一个自然语言算法工程师，更是一个热爱生活的编程少年，INFJ-A。

              坐标北京，互联网行业，喜欢电影、阅读、跑步，关注互联网行业、科技行业、新能源汽车行业以及FIRE运动。

              这个博客名称是因为我喜欢《Breaking Bad》(绝命毒师)，主角就叫老白，绰号海森堡，同时他在剧里从事化学zhidu，行话cook，所以我就取名为厨师海森堡的厨房，单纯是为了搞怪。

              这个博客我会总结一些技术相关话题，平时的感想，杂七杂八的话题，这里就是我的自留地了。

              如果你对我或者我写的东西感兴趣的话，欢迎交流📮346521888@qq.com。"


      


# 菜单配置
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "所有文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "类别"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5

# 文章页面配置
[page]
  # 是否使用系列导航
  seriesNavigation = true
  # 是否启用最后修改时间
  enableLastMod = true
  # 是否启用字数统计
  enableWordCount = true
  # 是否启用阅读时间估计
  enableReadingTime = true
   # 目录配置
  [page.toc]
    # 是否使用目录
    enable = true
    # 是否保持使用文章前面的静态目录
    keepStatic = false
    # 是否使侧边目录自动折叠展开
    auto = true
  # 文章页面的分享信息设置
  [page.share]
    enable = true
    Twitter = true
    Weibo = true